name: Delete
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: delete all_model    
      run: |
       mkdir git_hub
       cd git_hub
       git init
       export GITHUB_TOKEN=$token
       git config --global hub.protocol https
       git config --global user.name "AutumnCrocus"
       git config --global user.email "t4kicyis@gmail.com"
       git config --global remote.origin.url https://$token:x-oauth-basic@github.com/AutumnCrocus/shadow_sim.git
       git clone https://github.com/AutumnCrocus/shadow_sim.git
       git branch
       cd shadow_sim
       git rm model/*.pth
       git commit -m "test"
       git remote set-url origin https://$token:x-oauth-basic@github.com/AutumnCrocus/shadow_sim.git
       git config --list
       git push origin master
